import type { AssessmentConfig } from '../types/assessment'

const media = (name: string) => `/media/assessment/${name}`

export const assessmentConfig: AssessmentConfig = {
  version: 1,
  experienceId: 'a2o-image-assessment-placeholder',
  opening: {
    headline: '你而家嘅形象，同你想畀人嘅感覺一致嗎？',
    supportingText: '用幾條簡單問題，了解你目前最值得改善嘅位置。',
    cta: '開始診斷',
    resumeCta: '繼續診斷',
    note: '約 2 分鐘｜免費初步分析',
  },
  whatsappNumber: '85254077240',
  defaultResultId: 'untapped_image_potential',
  results: {
    untapped_image_potential: {
      id: 'untapped_image_potential',
      eyebrow: '你的初步形象分析',
      title: '未被發揮的形象潛力',
      summary: '你已經知道自己想改變，只是仍欠一套清晰、可持續執行的方法。',
      recommendation: '由場合、比例和固定配搭框架入手，會最快見到整體提升。',
    },
    professional_presence_gap: {
      id: 'professional_presence_gap',
      eyebrow: '你的初步形象分析',
      title: '專業存在感落差',
      summary: '你想呈現成熟可靠的感覺，但目前造型未完全支援你的職場角色。',
      recommendation: '先處理版型、輪廓與精神面貌，能更快建立可信任的第一印象。',
    },
    style_without_structure: {
      id: 'style_without_structure',
      eyebrow: '你的初步形象分析',
      title: '有風格方向，欠配搭結構',
      summary: '你對喜歡的感覺不陌生，但衣櫃與日常配搭仍未形成穩定系統。',
      recommendation: '建立個人色彩、比例和核心單品清單，會令每次選擇更簡單。',
    },
    low_energy_appearance: {
      id: 'low_energy_appearance',
      eyebrow: '你的初步形象分析',
      title: '精神感與整體狀態落差',
      summary: '你目前最值得優先處理的，是讓外觀更乾淨、有精神和有完整感。',
      recommendation: '由髮型、膚況和上半身輪廓開始，通常能帶來最明顯的即時改變。',
    },
  },
  scenes: [
    {
      id: 'scene-01',
      order: 1,
      enabled: true,
      sceneVideoUrl: media('scene-01-sofa-placeholder.mp4'),
      posterUrl: '/images/hero-vertical.jpg',
      transitionVideoUrl: media('transition-01-placeholder.mp4'),
      questionCueSeconds: 3.4,
      idleMode: 'hold-last-frame',
      caption: '先由你最想改變的地方開始。',
      question: {
        id: 'q1',
        type: 'single',
        title: '你目前最大嘅形象困擾係咩？',
        options: [
          { id: 'q1_a', label: '買咗好多衫，但仍然唔識襯', value: 'wardrobe_confusion', score: { style_without_structure: 3 } },
          { id: 'q1_b', label: '望落唔夠精神', value: 'low_energy', score: { low_energy_appearance: 3 } },
          { id: 'q1_c', label: '工作見人時唔夠成熟專業', value: 'professional_gap', score: { professional_presence_gap: 3 } },
          { id: 'q1_d', label: '整體形象太普通', value: 'too_generic', score: { untapped_image_potential: 3 } },
        ],
      },
    },
    {
      id: 'scene-02',
      order: 2,
      enabled: true,
      sceneVideoUrl: media('scene-02-wardrobe-placeholder.mp4'),
      posterUrl: '/images/hero-vertical-2.jpg',
      transitionVideoUrl: media('transition-02-placeholder.mp4'),
      questionCueSeconds: 3.4,
      idleMode: 'hold-last-frame',
      caption: '你最常出現的場合，決定最需要先建立的形象。',
      question: {
        id: 'q2',
        type: 'single',
        title: '你最想喺邊個場合提升形象？',
        options: [
          { id: 'q2_a', label: '返工／見客', value: 'work', score: { professional_presence_gap: 2 } },
          { id: 'q2_b', label: '約會／社交', value: 'social', score: { untapped_image_potential: 2 } },
          { id: 'q2_c', label: '面試／轉工', value: 'interview', score: { professional_presence_gap: 3 } },
          { id: 'q2_d', label: '日常生活', value: 'daily', score: { style_without_structure: 2 } },
        ],
      },
    },
    {
      id: 'scene-03',
      order: 3,
      enabled: true,
      sceneVideoUrl: media('scene-03-mirror-placeholder.mp4'),
      posterUrl: '/images/hero-vertical-3.jpg',
      transitionVideoUrl: media('transition-03-placeholder.mp4'),
      questionCueSeconds: 3.4,
      idleMode: 'hold-last-frame',
      caption: '理想形象，要由你希望別人感受到的特質出發。',
      question: {
        id: 'q3',
        type: 'multi',
        maxSelections: 3,
        title: '你最希望別人點樣形容你？',
        subtitle: '最多選擇 3 項',
        options: [
          { id: 'q3_a', label: '成熟可靠', value: 'mature', score: { professional_presence_gap: 1 } },
          { id: 'q3_b', label: '專業可信', value: 'credible', score: { professional_presence_gap: 2 } },
          { id: 'q3_c', label: '乾淨精神', value: 'fresh', score: { low_energy_appearance: 2 } },
          { id: 'q3_d', label: '有品味', value: 'tasteful', score: { style_without_structure: 2 } },
        ],
      },
    },
    {
      id: 'scene-04',
      order: 4,
      enabled: true,
      sceneVideoUrl: media('scene-04-consultation-placeholder.mp4'),
      posterUrl: '/images/team.jpg',
      transitionVideoUrl: media('transition-04-placeholder.mp4'),
      questionCueSeconds: 3.4,
      idleMode: 'hold-last-frame',
      caption: '改善次序清楚，整個轉變先會容易持續。',
      question: {
        id: 'q4',
        type: 'multi',
        maxSelections: 3,
        title: '你覺得自己最需要改善邊幾項？',
        subtitle: '最多選擇 3 項',
        options: [
          { id: 'q4_a', label: '髮型', value: 'hair', score: { low_energy_appearance: 2 } },
          { id: 'q4_b', label: '皮膚／精神面貌', value: 'grooming', score: { low_energy_appearance: 3 } },
          { id: 'q4_c', label: '身形比例', value: 'proportion', score: { untapped_image_potential: 2 } },
          { id: 'q4_d', label: '穿搭配搭', value: 'styling', score: { style_without_structure: 3 } },
        ],
      },
    },
    {
      id: 'scene-05',
      order: 5,
      enabled: true,
      sceneVideoUrl: media('scene-05-hero-placeholder.mp4'),
      posterUrl: '/images/hero-page.png',
      questionCueSeconds: 3.4,
      idleMode: 'hold-last-frame',
      caption: '最後，看看你準備在甚麼時候開始。',
      question: {
        id: 'q5',
        type: 'single',
        title: '你希望幾時真正開始改變？',
        options: [
          { id: 'q5_a', label: '兩星期內', value: 'two_weeks', score: { untapped_image_potential: 2 } },
          { id: 'q5_b', label: '一個月內', value: 'one_month', score: { untapped_image_potential: 1 } },
          { id: 'q5_c', label: '三個月內', value: 'three_months', score: { style_without_structure: 1 } },
          { id: 'q5_d', label: '暫時先了解', value: 'researching', score: { untapped_image_potential: 1 } },
        ],
      },
    },
  ],
}
